local-ai:
	docker run -ti -p 8080:8080 localai/localai:v2.9.0-ffmpeg-core phi-2

up:
	npx flowise start

docker.up:
	docker-compose up -d

# docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
